name: Autobuild

on:
  push:
    branches: [main]
  workflow_dispatch:

jobs:
  build:
    name: Build

    runs-on: windows-latest
    steps:
      - uses: llvm/actions/install-ninja@main

      - uses: actions/checkout@v2
        with:
          fetch-depth: 1
          submodules: true

      - name: Build
        run: |
          mkdir build
          cd build
          cmake .. -G"Visual Studio 17 2022" -A x64
          cmake --build . --config Release

      - name: Create artifacts
        run: |
          mkdir MAXWELL
          move build\Release\MAXWELL.dll MAXWELL\MAXWELL.dll
          move build\Release\MAXWELL.exe MAXWELL\MAXWELL.exe
          move README.md MAXWELL\README.txt
          7z a MAXWELL.zip MAXWELL\

      - name: Create release
        uses: marvinpinto/action-automatic-releases@v1.1.0
        env:
          ACTIONS_ALLOW_UNSECURE_COMMANDS: "true"
        with:
          repo_token: "${{ secrets.GITHUB_TOKEN }}"
          automatic_release_tag: "autobuild"
          prerelease: false
          title: "Autobuild"
          files: |
            MAXWELL.zip
